name: Deploy to Amazon ECS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ecsdjangorepo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo $ECR_REGISTRY
          docker build -t public.ecr.aws/y2a7t2w8/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push public.ecr.aws/y2a7t2w8/$ECR_REPOSITORY:$IMAGE_TAG
          # echo "::set-output name=image::public.ecr.aws/y2a7t2w8/$ECR_REPOSITORY:$IMAGE_TAG"